name: Build GUI Applications

on:
  push:
    tags:
      - 'v*'  # Se déclenche pour les tags de version
  pull_request:
    branches:
      - main  # Se déclenche pour les PRs vers main
  workflow_dispatch:  # Permet le déclenchement manuel

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y \
            libwxbase3.2-1 \
            libwxgtk3.2-1 \
            libwxgtk-media3.2-1 \
            libwxgtk-webview3.2-1 \
            python3-wxgtk4.0 \
            python3-wxgtk-media4.0 \
            python3-wxgtk-webview4.0 \
            libgtk-3-dev \
            python3-pip \
            python-is-python3

      - name: Install Gooey
        run: |
          pip install attrdict3
          pip install gooey
          pip install pyinstaller

      - name: Install user dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Make package
        run: |
          pyinstaller --clean -y --dist ./dist/linux build_gui.spec

      - uses: actions/upload-artifact@v4
        with:
          name: med_to_csv_linux
          path: ./dist/linux

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Gooey
        run: |
          python -m pip install --upgrade pip
          pip install gooey
          pip install Pyinstaller

      - name: Install user dependencies
        run: |
          if (Test-Path -Path "requirements.txt") {
              pip install -r requirements.txt
          }

      - name: Make package
        run: |
          pyinstaller --clean -y --dist ./dist/windows build_gui.spec

      - uses: actions/upload-artifact@v4
        with:
          name: med_to_csv_windows
          path: ./dist/windows